name: picker
description: Flutter plugin for selecting images from the Android and iOS, taking new pictures with the camera and saves on Gallery
homepage: https://github.com/jonataslaw/picker
version: 2.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: app.flutter.plugins.picker
        pluginClass: ImagePickerPlugin
      ios:
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  video_player: ^2.0.2
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <3.0.0"
